const DecisionTree = require('./src/DecisionNode')
const DecisionTreeConsole = require('./src/DecisionTreeConsole')
const dc1 = new DecisionTree("What you want to do?")
const dc12 = new DecisionTree("What you want to eat?", "Eat")
const dc13 = new DecisionTree("When you want to sleep?", "Sleep")
const dc121 = new DecisionTree("What is the brand of biscuit?", "Biscuit")
const dc122 = new DecisionTree("What type of bread?", "Bread")
const dc131 = new DecisionTree("What you want to do before that?", "1")
const dc132 = new DecisionTree(null, "now")
const dc1211 = new DecisionTree(null, "Parle G")
const dc1212 = new DecisionTree(null, "Britania")
const dc1221 = new DecisionTree(null, "Wheat")
const dc1222 = new DecisionTree(null, "Brown")
const dc1223 = new DecisionTree(null, "Multi grain")
const dc1321 = new DecisionTree(null, "meditate")
const dc1322 = new DecisionTree(null, "Hear songs")
dc121.addChild(dc1211)
dc121.addChild(dc1212)
dc122.addChild(dc1221)
dc122.addChild(dc1222)
dc122.addChild(dc1223)
dc131.addChild(dc1321)
dc131.addChild(dc1322)
dc12.addChild(dc121)
dc12.addChild(dc122)
dc13.addChild(dc131)
dc13.addChild(dc132)
dc1.addChild(dc12)
dc1.addChild(dc13)

const dtc = new DecisionTreeConsole(dc1)
dtc.parse()
